
version: 2

references:
  defaults: &defaults
    working_directory: ~/app
    docker:
      - image: circleci/node:8

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      #- run: npm test

  deploy:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
